apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  DB_USERNAME: {{ .Values.api.env.DB_USERNAME | b64enc }}
  DB_PASS: {{ .Values.api.env.DB_PASS | b64enc }}
{{- if .Values.vllm.enabled }}
  DEPLOYED_LLM_TOKEN: {{ .Values.vllm.huggingFace.hfToken | b64enc }}
{{- else }}
  DEPLOYED_LLM_TOKEN: {{ .Values.deployedllm.accessToken | b64enc }}
{{- end }}
