apiVersion: v2
name: statbot
description: A Helm chart for deploying the Statbot API and UI
type: application
version: 0.0.5
appVersion: 0.0.5

dependencies:
  - name: llm-serving
    version: 0.1.3
    repository: https://dscc-admin-ch.github.io/helm-charts
    alias:  vllm