{{/*
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    helm.sh/chart: lomas-server-0.5.0
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.5.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - name: amqp
      port: 5672
    - name: dist
      port: 25672
    - name: epmd
      port: 4639
    - name: http-stats
      port: 15672
  selector:
    app.kubernetes.io/name: rabbitmq
*/}}
