{{- if not .Values.admin.client_secret_existing_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lomas-admin.secretName" . }}
  labels:
    {{ include "lomas.labels" . | nindent 4}}
type: Opaque
data:
  client-secret: {{ required ".Values.admin.client_secret or existing secret must be set." .Values.admin.client_secret | b64enc }}
{{- end }}