{{- $creds := .Values.server.runtime_args.private_db_credentials }}
{{- $secretNames := (include "lomas-service.private-db-credentials-secrets" $) | fromYamlArray }}

{{- range $i, $cred := $creds }}
  {{- if not $cred.existing_secret }}
    {{- $secretName := index $secretNames $i }}
    {{- $filtered := dict }}
    {{- range $k, $v := $cred }}
      {{- if ne $k "existing_secret" }}
        {{- $_ := set $filtered $k $v }}
      {{- end }}
    {{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{ include "lomas.labels" $ | nindent 4 }}
type: Opaque
data:
  private-db-credentials: {{ toJson $filtered | b64enc }}

---
  {{- end }}
{{- end }}