apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-serving.fullname" . }}
  labels:
     {{- include "llm-serving.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "llm-serving.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.networking.port.number }}
    protocol: TCP
    nodePort: {{ .Values.networking.port.nodePort }}
  type: NodePort