apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
  type: ClusterIP
